### ISSUE TITLE
Rserve failures

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#192]
I get these two failures on running `rake spec` after cloning Daru repo on a cloud computer. 

```ruby
Failures:

  1) Daru rserve extension Daru::Vector#to_REXP converts to and from R data
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: @r = Rserve::Connection.new
          
          Rserve::Connection::RserveNotStartedError:
            Can't start Rserve
          # /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:83:in `rescue in initialize'
          # /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:66:in `initialize'
          # ./spec/extensions/rserve_spec.rb:7:in `new'
          # ./spec/extensions/rserve_spec.rb:7:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Errno::ECONNREFUSED:
          #   Connection refused - connect(2) for "127.0.0.1" port 6311
          #   /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:104:in `initialize'

     1.2) Failure/Error: @r.close
          
          NoMethodError:
            undefined method `close' for nil:NilClass
            Did you mean?  clone
          # ./spec/extensions/rserve_spec.rb:11:in `block (2 levels) in <top (required)>'

  2) Daru rserve extension Daru::DataFrame#to_REXP converts to and from R data
     Got 0 failures and 2 other errors:

     2.1) Failure/Error: @r = Rserve::Connection.new
          
          Rserve::Connection::RserveNotStartedError:
            Can't start Rserve
          # /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:83:in `rescue in initialize'
          # /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:66:in `initialize'
          # ./spec/extensions/rserve_spec.rb:7:in `new'
          # ./spec/extensions/rserve_spec.rb:7:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Errno::ECONNREFUSED:
          #   Connection refused - connect(2) for "127.0.0.1" port 6311
          #   /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:104:in `initialize'

     2.2) Failure/Error: @r.close
          
          NoMethodError:
            undefined method `close' for nil:NilClass
            Did you mean?  clone
          # ./spec/extensions/rserve_spec.rb:11:in `block (2 levels) in <top (required)>'

```

Do I need to open a port or something?

**Comment by v0dro** [comment]
I think Rserve needs R installed. See this: https://github.com/v0dro/daru/blob/master/CONTRIBUTING.md#installing-daru-development-dependencies

Let me know if it works for you.

**Comment by lokeshh** [comment]
Its working. Thanks!
