### ISSUE TITLE
from_sql not working

### ISSUE THREAD

**Issue by dansbits** [v0dro/daru#29]
DataFrame.from_sql is not working for me with the follwing:

```
conn = DBI.connect("DBI:SQLite3:daru_test")
df = Daru::DataFrame.from_sql(conn, 'select * from accounts')
```
I get this error:
```
RuntimeError: can't add a new key into hash during iteration
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/dbi-0.4.5/lib/dbi/columninfo.rb:49:in `block in initialize'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/dbi-0.4.5/lib/dbi/columninfo.rb:42:in `each_key'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/dbi-0.4.5/lib/dbi/columninfo.rb:42:in `initialize'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/dbi-0.4.5/lib/dbi/handles/statement.rb:185:in `new'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/dbi-0.4.5/lib/dbi/handles/statement.rb:185:in `block in column_info'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/dbi-0.4.5/lib/dbi/handles/statement.rb:185:in `collect'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/dbi-0.4.5/lib/dbi/handles/statement.rb:185:in `column_info'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/daru-0.1.0/lib/daru/io/io.rb:131:in `from_sql'
	from /Users/daniel/.rvm/gems/ruby-2.2.2/gems/daru-0.1.0/lib/daru/dataframe.rb:72:in `from_sql'
	from (irb):9
	from /Users/daniel/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
```
This appears to be an issue with the way the dbi column_info method is being used in IO.from_sql.

I forked the repository and have a working version now but wanted to make sure this isn't a known issue before submitting a PR. Any guidance is appreciated.

Thanks!
Dan

**Comment by v0dro** [comment]
Yes this is a known issue. I had ported this feature directly from statsample and couldn't write tests because of time constraints.

If you have a working version please send me a PR so that I can update the gem accordingly.

Also, don't forget to write tests!

Great work! Thanks!

**Comment by dansbits** [comment]
Ok. I just created the PR. Let me know if you have any thoughts or concerns.
